# codemagic.yaml SIMPLIFICADO para o projeto federacaomad
# AVISO: Contém google-services.json no repositório — não é recomendado por segurança

workflows:
  android-debug-build-insecure:
    name: Federacaomad Android Debug Build (google-services.json no repo)

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true

    environment:
      flutter: stable  # ou "3.22.1" por exemplo
      JVM_ARGS: "-Xmx8192M"

    scripts:
      - name: Configurar Flutter
        script: |
          flutter config --enable-android
          flutter doctor

      - name: Limpar cache do Flutter
        script: |
          flutter clean

      - name: Obter dependências Flutter
        script: |
          flutter pub get

      - name: Construir APK Debug
        script: |
          cd $CM_BUILD_DIR
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
